apiVersion: v1
kind: Service
metadata:
  name: zoobayd-backend
  namespace: zoobayd
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: zoobayd-backend