apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-profiles
  namespace: zoobayd
data:
  small:
    cpu: 200m
    memory: 256Mi
  medium:
    cpu: 500m
    memory: 512Mi
  large:
    cpu: 1000m
    memory: 1Gi
  xl:
    cpu: 2000m
    memory: 2Gi
  gpu:
    cpu: 4000m
    memory: 8Gi
    nvidia.com/gpu: 1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: zoobayd
spec:
  hard:
    limits.cpu: 32
    limits.memory: 64Gi
    requests.storage: 500Gi
    requests.nvidia.com/gpu: 4
    count/deployments.apps: 20
    count/statefulsets.apps: 5
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: zoobayd
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    default:
      cpu: 500m
      memory: 512Mi
    min:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 4
      memory: 8Gi