apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoobayd-platform
  labels:
    app: zoobayd-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zoobayd-platform
  template:
    metadata:
      labels:
        app: zoobayd-platform
    spec:
      containers:
      - name: backend
        image: zoobayd-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
      - name: frontend
        image: zoobayd-frontend:latest
        ports:
        - containerPort: 3001
      
---
apiVersion: v1
kind: Service
metadata:
  name: zoobayd-service
spec:
  selector:
    app: zoobayd-platform
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer