apiVersion: v1
kind: LimitRange
metadata:
  name: zoobayd-limits
  namespace: zoobayd
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    max:
      cpu: 2
      memory: 2Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Container