apiVersion: v1
kind: ResourceQuota
metadata:
  name: zoobayd-quota
  namespace: zoobayd
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    services.loadbalancers: "2"
    count/deployments.apps: "10"
    count/statefulsets.apps: "5"
    count/jobs.batch: "20"
    count/cronjobs.batch: "10"