apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-budget-alerts
  namespace: monitoring
data:
  budgets.json: |
    {
      "Budgets": [
        {
          "BudgetName": "Monthly-EC2-Budget",
          "BudgetLimit": {
            "Amount": "5000",
            "Unit": "USD"
          },
          "TimeUnit": "MONTHLY",
          "BudgetType": "COST",
          "CostFilters": {
            "Service": ["Amazon Elastic Compute Cloud"]
          },
          "NotificationsWithSubscribers": [
            {
              "Notification": {
                "NotificationType": "ACTUAL",
                "ComparisonOperator": "GREATER_THAN",
                "Threshold": 80,
                "ThresholdType": "PERCENTAGE"
              },
              "Subscribers": [
                {
                  "SubscriptionType": "SNS",
                  "Address": "arn:aws:sns:us-east-1:123456789012:budget-alerts"
                }
              ]
            }
          ]
        },
        {
          "BudgetName": "Total-Monthly-Budget",
          "BudgetLimit": {
            "Amount": "10000",
            "Unit": "USD"
          },
          "TimeUnit": "MONTHLY",
          "BudgetType": "COST",
          "NotificationsWithSubscribers": [
            {
              "Notification": {
                "NotificationType": "ACTUAL",
                "ComparisonOperator": "GREATER_THAN",
                "Threshold": 85,
                "ThresholdType": "PERCENTAGE"
              },
              "Subscribers": [
                {
                  "SubscriptionType": "SNS",
                  "Address": "arn:aws:sns:us-east-1:123456789012:budget-alerts"
                }
              ]
            },
            {
              "Notification": {
                "NotificationType": "FORECASTED",
                "ComparisonOperator": "GREATER_THAN",
                "Threshold": 100,
                "ThresholdType": "PERCENTAGE"
              },
              "Subscribers": [
                {
                  "SubscriptionType": "SNS",
                  "Address": "arn:aws:sns:us-east-1:123456789012:budget-alerts-critical"
                }
              ]
            }
          ]
        }
      ]
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: budget-sync
  namespace: monitoring
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aws-cli
            image: amazon/aws-cli
            command:
            - /bin/sh
            - -c
            - |
              aws budgets describe-budgets --account-id $AWS_ACCOUNT_ID > /tmp/current-budgets.json
              if ! diff /tmp/current-budgets.json /etc/aws-budgets/budgets.json; then
                aws budgets update-budget --account-id $AWS_ACCOUNT_ID --new-budget file:///etc/aws-budgets/budgets.json
              fi
            env:
            - name: AWS_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-account
                  key: account-id
            volumeMounts:
            - name: budget-config
              mountPath: /etc/aws-budgets
          volumes:
          - name: budget-config
            configMap:
              name: aws-budget-alerts