apiVersion: batch/v1
kind: CronJob
metadata:
  name: cost-reporter
  namespace: monitoring
spec:
  schedule: "0 1 * * *"  # Daily at 1 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reporter
            image: kubecost/cost-analyzer:latest
            args: ["--report-mode"]
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: secret-key
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-creds
                  key: webhook-url
            volumeMounts:
            - name: config
              mountPath: /config
          volumes:
          - name: config
            configMap:
              name: cost-report-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cost-report-config
  namespace: monitoring
data:
  config.yaml: |
    report:
      clusters:
        - name: zoobayd
          namespace:
            include:
              - zoobayd
              - monitoring
          aggregation:
            - type: namespace
            - type: pod
            - type: node
          metrics:
            - name: cpu_cost
              window: 24h
            - name: memory_cost
              window: 24h
            - name: network_cost
              window: 24h
            - name: pv_cost
              window: 24h
      output:
        format: 
          - json
          - html
        destinations:
          - s3
          - slack
      alerts:
        - type: budget_exceeded
          threshold: 1000
          window: 24h
        - type: cost_increase
          threshold: 30
          window: 24h