apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-node-termination-handler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: aws-node-termination-handler
  template:
    metadata:
      labels:
        app: aws-node-termination-handler
    spec:
      containers:
      - name: aws-node-termination-handler
        image: amazon/aws-node-termination-handler:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPOT_ITN_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/spot-interruption-queue"
        - name: WEBHOOK_URL
          value: "http://slack-notifier/notification"
        - name: DRY_RUN
          value: "false"
        - name: CORDON_ONLY
          value: "false"
        - name: TAINT_NODE
          value: "true"
        - name: JSON_LOGGING
          value: "true"
        - name: WEBHOOK_PROXY
          value: ""
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs