apiVersion: v1
kind: ServiceAccount
metadata:
  name: zoobayd-backend-sa
  namespace: zoobayd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zoobayd-backend-role
  namespace: zoobayd
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zoobayd-backend-rolebinding
  namespace: zoobayd
subjects:
- kind: ServiceAccount
  name: zoobayd-backend-sa
  namespace: zoobayd
roleRef:
  kind: Role
  name: zoobayd-backend-role
  apiGroup: rbac.authorization.k8s.io