name: Zoobayd Platform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/frontend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::727417435909:role/github-actions-role
        aws-region: us-east-1
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    
    - name: Install Dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install
    
    - name: Build Frontend
      run: npm run build

    - name: Deploy to S3
      run: aws s3 sync build/ s3://zoobayd-platform/ --delete