name: Zoobayd Platform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: zoobayd-frontend:latest
    
    - name: Copy build files
      run: |
        container_id=$(docker create zoobayd-frontend:latest)
        docker cp $container_id:/usr/src/app/build ./build
        docker rm $container_id
    
    - name: Deploy to S3
      run: aws s3 sync build/ s3://zoobayd-platform/ --delete