name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install Dependencies
      run: |
        npm install
        npm run bootstrap
    
    - name: Run Linter
      run: npm run lint
    
    - name: Run Tests
      run: npm test
    
    - name: Build Project
      run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./packages/backend
        push: true
        tags: zoobayd/backend:latest
    
    - name: Build and Push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./packages/frontend
        push: true
        tags: zoobayd/frontend:latest
    
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG }}
        command: apply -f k8s/deployment.yaml