name: Zoobayd Platform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install Dependencies
      run: |
        npm install
        npm install -g lerna
        lerna bootstrap
    
    - name: Lint Code
      run: |
        npm run lint
    
    - name: Run Backend Tests
      run: |
        cd packages/backend
        npm test
    
    - name: Run Frontend Tests
      run: |
        cd packages/frontend
        npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Production
      # This is a placeholder. Replace with your actual deployment strategy
      run: |
        echo "Deploying to production server"
        # Add your deployment commands here
        
    - name: Notify Deployment
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment successful!
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
