apiVersion: v1
kind: Node
metadata:
  name: zoobayd-worker-1
spec:
  taints:
  - key: dedicated
    value: zoobayd
    effect: NoSchedule
  - key: instance-type
    value: spot
    effect: PreferNoSchedule
---
apiVersion: v1
kind: Node
metadata:
  name: zoobayd-worker-2
spec:
  taints:
  - key: dedicated
    value: zoobayd
    effect: NoSchedule
  labels:
    instance-type: c5.xlarge
    node-role.kubernetes.io/worker: ""
---
apiVersion: v1
kind: Node
metadata:
  name: zoobayd-worker-3
spec:
  taints:
  - key: dedicated
    value: zoobayd
    effect: NoSchedule
  labels:
    instance-type: c5.2xlarge
    node-role.kubernetes.io/worker: ""